[package]
name = "voiceapp-frontend"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "voiceapp-frontend"
path = "src/main.rs"

[dependencies]
iced = { version = "0.13.1", features = ["tokio"] }
tokio = { version = "1.48.0", features = ["full"] }