[package]
name = "voiceapp-server"
version = "0.0.1"
edition = "2021"

[dependencies]
voiceapp-protocol = { path = "../protocol" }
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.3"
rand = "0.8.5"
dashmap = "6.1.0"
thiserror = "2"