[package]
name = "extras"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "music_bot"
path = "src/bin/music_bot.rs"

[dependencies]
voiceapp-sdk = { path = "../sdk" }
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.3"
hound = "3.5"
